version: '3'

services:
  merenda_mais:
    build: .
    network_mode: host
    working_dir: /app
    privileged: true
    volumes:
     - "./:/app"
    command: |
     bash -c "
     npm install
     npm start
     "
